version: '3.3'

services:
  notification:
    container_name: notification
    image: kimdahui/notification
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8010:8010"
    environment:
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
      - CONFIG_USERNAME=${CONFIG_USERNAME}
    networks:
      - jenkins-project_socon-net

networks:
  jenkins-project_socon-net:
    external: true

