version: '3.3'

services:
  user:
    container_name: user
    image: kimdahui/user
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8040:8040"
    environment:
      - CONFIG_PASSWORD=${CONFIG_PASSWORD}
      - CONFIG_USERNAME=${CONFIG_USERNAME}
    networks:
      - jenkins-project_socon-net

networks:
  jenkins-project_socon-net:
    external: true

